name: CheCko wallet build, lint, and test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: CheCko - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: git submodule update --init --recursive
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: wget https://github.com/protocolbuffers/protobuf/releases/download/v27.2/protoc-27.2-linux-x86_64.zip -o ../protoc-27.2-linux-x86_64.zip
      - run: apt install unzip
      - run: mkdir -p ../protoc; cd ../protoc; unzip ../protoc-27.2-linux-x86_64.zip
      - run: yarn
      - run: PATH=$PATH:$PWD/../protoc/bin yarn build-wasm
      - run: yarn build
      - run: yarn build-bex
      - run: yarn lint
