name: CheCko wallet build, lint, and test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: CheCko - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: git submodule update --init --recursive
      - run: yarn
      - run: yarn build-wasm
      - run: yarn build
      - run: yarn build-bex
      - run: yarn lint
